### ISSUE TITLE
Error While running the Script

### ISSUE THREAD

**Issue by ranabanerjee15** [ironmansoftware/ud-bginfo#1]
Hello Adam,

First of all,  I would like to say, EXCELLENT WORK. I really appreciate whatever you are doing.
I did not get much time to explore all the aspects of Universal Dashboard but whatever I have so far, just love it. I have been showcasing them at work with different departments too.

now coming back to the issue, I tried to run the ud-bginfo dashboard. but I get this following error.

I can browse to the dashboard but it comes up without any tiles or cards. Please advise what am I doing wrong?

PS C:\> C:\Users\rana\Documents\WindowsPowerShell\Modules\ud-bginfo\1.1\ud-bginfo.ps1
New-UDDashboard : Parameter set cannot be resolved using the specified named parameters.
At C:\Users\rana\Documents\WindowsPowerShell\Modules\ud-bginfo\1.1\ud-bginfo.ps1:26 char:14
+ ... Dashboard = New-UDDashboard -Title "$env:ComputerName - BGINFO" -Cont ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SyntaxError: (UniversalDashboard.Models.Dashboard:Dashboard) [New-UDDashboard], ParameterBindingException
    + FullyQualifiedErrorId : UniversalDashboard.Cmdlets.NewDashboardCommand
 

Name         Port Running
----         ---- -------
Dashboard20 10000    True

**Comment by adamdriscoll** [comment]
I fixed this and published a new version. Sorry about that!
