### ISSUE TITLE
New-UDDashboard parameter EndpointInitializationScript

### ISSUE THREAD

**Issue by stefanstranger** [ironmansoftware/ud-bginfo#2]
New-UDDashboard cmdlet from the Module  UniversalDashboard.Community version 2.0.1 does not have  parameter EndpointInitializationScript parameter but a parameter EndpointInitialization.

/Stefan

**Comment by LuizHAP** [comment]
I have same problem. @stefanstranger u know how to fix this?

Att

**Comment by zubair-rana** [comment]
having the same issue as @stefanstranger and @LuizHAP - any help would be appreciated @adamdriscoll
"New-UDDashboard : A parameter cannot be found that matches parameter name 'EndpointInitializationScript'."

**Comment by adamdriscoll** [comment]
Published 2.0 to the gallery that works with UD 2.0.

**Comment by febox6** [comment]
I'm still having this problem with  UniversalDashboard.Community version 2.4.0
