### ISSUE TITLE
Exception with Invoke with "0", Attempted to divide by "0"

### ISSUE THREAD

**Issue by zachary-b** [ironmansoftware/ud-bginfo#3]
Using a trial version of the Universal Dashboard, version 2.3.1.
Using ud-bginfo version 2.0.
Running locally on desktop computer.

If you run New-StorageCard on a computer that has a DVD drive, it throws an exception with the error "Attempted to divide by zero." (at least from what I've seen).
Error from page: "Exception calling "Invoke" with "0" argument(s): "Attempted to divide by zero.""
Error from PS is the same: New-UDPage : Exception calling "Invoke" with "0" argument(s): "Attempted to divide by zero."

Changing the psm1 function for New-StorageCard to include: ` | Where {$_.DriveType -ne "5"}` fixed the issue I ran into. Not sure if including the DVD was by design. I'm perfectly fine with keeping that modification if it's not an actual issue.

**Comment by adamdriscoll** [comment]
Makes sense to remove those. I committed a change to do so.

**Comment by bobmihada** [comment]
Where-object  size -gt 0
